# Generated by Django 4.0.3 on 2022-04-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_project_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
