# Generated by Django 4.0.4 on 2022-04-29 14:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_sentance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sentance',
            new_name='Sentence',
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='sentance_id',
            new_name='sentence_id',
        ),
    ]
