# Generated by Django 4.0.4 on 2022-11-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_sentance_sentence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='number',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
