# Generated by Django 4.0.4 on 2022-11-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_sentence_number_delete_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sentence',
        ),
    ]
